# Generated by Django 2.2.1 on 2019-05-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee11111',
        ),
    ]
