# Generated by Django 2.2.1 on 2019-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapplication', '0002_auto_20190518_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
